//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Productld { get; set; }
        public double Price { get; set; }
        public int Statuss { get; set; }
        public System.DateTime CeatedOnUtc { get; set; }
    }
}
