//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public int Categoryid { get; set; }
        public string ShortDes { get; set; }
        public string FullDescription { get; set; }
        public double Price { get; set; }
        public double PriceDiscount { get; set; }
        public int Typeld { get; set; }
        public string Slug { get; set; }
        public int Brandld { get; set; }
        public bool Deleted { get; set; }
        public bool ShowOnHomePage { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
    }
}
